<a href="https://colab.research.google.com/github/YangHyunu/SKT-FLY-AI-5/blob/main/1%EC%A3%BC%EC%B0%A8/1%EC%9D%BC_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## 라이브러리 임포트

In [ ]:
import numpy as np
np.__version__

'1.25.2'

# 파이썬 리스트와 처리 속도 비교

In [ ]:
import random
my_arr=[random.random() for i in range(1_000_000)]
type(my_arr)


list

In [ ]:
%%timeit
import statistics as stat
stat.mean(my_arr)


639 ms ± 13.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [ ]:
%%timeit
arr = np.array(my_arr)
type(arr)
np.mean(arr)

48.2 ms ± 388 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 배열생성

In [ ]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
# arr1 = np.array([-1,-2,-3,-4,-5])
print(arr)
# arr1

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# print(arr.shape)
# print(arr.ndim)
# arr.dtype
arr.size
len(arr)

(2, 2, 2)


2

## 생성과 초기화

In [ ]:
arr_zero = np.zeros((3,2))
arr_zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
np.full((2,3),-1)

array([[-1, -1, -1],
       [-1, -1, -1]])

In [ ]:
arr = np.array([[[1,2],[3,4]],
 [[5,6],[7,8]]])
np.zeros_like(arr)
np.zeros_like(arr.shape)

array([0, 0, 0])

In [ ]:
# list(range(10))

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 인덱싱, 슬라이싱

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
arr= np.array([[1,2,3],[4,5,6]])
# print(arr[:-3])
# arr[3:-1]
arr[1,1] # == arr[1][1]

5

## * 불리언 인덱싱 *


In [ ]:
arr = np.array([1,2,3,4,5])
idx = np.array([True,False,True,False,True])
print(arr[idx])
print(arr[arr>3])

[1 3 5]
[4 5]


## fancy(팬시) 인덱싱


In [ ]:
arr = np.array([1,2,3,4,5])
# idx = np.array([1,3])
idx = np.array([[1,3],[0,1]])
arr[idx]

array([[2, 4],
       [1, 2]])

In [ ]:
arr = np.array([1,2,3,4,5])
arr[0]=-1
arr

array([-1,  2,  3,  4,  5])

## 형태 변환 <배열>

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr.shape

(6,)

- 배열을 새로운 형태로 변환
  ex 1차원 배열을 2차원으로.

In [ ]:
arr1=arr.reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

- 배열 평탄화 , 배열을 1차원 벡터로

In [ ]:
arr2 = arr1.reshape(-1) #
arr2
arr1.flatten() #
arr1.ravel()

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr3 = arr1.reshape(1,2,3)
print(arr3)
print(arr1.reshape(1,2,-1))
print(arr1.reshape(1,-1,1))

[[[1 2 3]
  [4 5 6]]]
[[[1 2 3]
  [4 5 6]]]
[[[1]
  [2]
  [3]
  [4]
  [5]
  [6]]]


In [ ]:
arr4=arr.reshape(2,3)
arr4

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# np.sum(arr4)
print(np.sum(arr4,axis=0))
np.sum(arr4,axis=1)

[5 7 9]


array([ 6, 15])

In [ ]:
np.mean(arr4,axis=0)

array([2.5, 3.5, 4.5])

In [ ]:
arr = np.array([1,2,3,4,5,6])
arr[np.newaxis,:]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
arr[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
np.savez('my_data.npz',train=arr)

In [ ]:
data = np.load('my_data.npz')
data['train']

array([1, 2, 3, 4, 5, 6])